"""empty message

Revision ID: 0d75536100cc
Revises: 379e82c20292
Create Date: 2024-04-27 13:31:31.942857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0d75536100cc'
down_revision = '379e82c20292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationhistories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_conversationhistories_chatbot_id_chatbots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversationhistories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversationhistories'))
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('conversation_history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_chats_chatbot_id_chatbots')),
    sa.ForeignKeyConstraint(['conversation_history_id'], ['conversationhistories.id'], name=op.f('fk_chats_conversation_history_id_conversationhistories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.drop_table('conversation_history')
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_history_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='fk_chat_chatbot_id_chatbots'),
    sa.ForeignKeyConstraint(['conversation_history_id'], ['conversation_history.id'], name='fk_chat_conversation_history_id_conversation_history'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chat_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_chat')
    )
    op.create_table('conversation_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('messages', sqlite.JSON(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chatbot_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='fk_conversation_history_chatbot_id_chatbots'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_conversation_history_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_conversation_history')
    )
    op.drop_table('chats')
    op.drop_table('conversationhistories')
    # ### end Alembic commands ###
