"""empty message

Revision ID: 11a174853f00
Revises: e7c9bc3a551c
Create Date: 2024-10-21 18:45:23.485416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a174853f00'
down_revision = 'e7c9bc3a551c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telafric_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('pin_code', sa.String(length=6), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telafric_subscribers'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['telafric_subscribers.id'], name=op.f('fk_payments_subscriber_id_telafric_subscribers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.drop_table('tel_afric_subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tel_afric_subscribers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('pin_code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tel_afric_subscribers')
    )
    op.drop_table('payments')
    op.drop_table('telafric_subscribers')
    # ### end Alembic commands ###
