"""empty message

Revision ID: 1f4f86d83ce6
Revises: 6bee14f61300
Create Date: 2024-04-28 16:31:08.919622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4f86d83ce6'
down_revision = '6bee14f61300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('conversation_history_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('conversation_history_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
