"""empty message

Revision ID: 23aa322ca2ac
Revises: 0d75536100cc
Create Date: 2024-04-27 13:34:38.332038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aa322ca2ac'
down_revision = '0d75536100cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationhistories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationhistories', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
