"""empty message

Revision ID: 2707447ef4d4
Revises: 11a174853f00
Create Date: 2024-12-11 08:15:29.180314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2707447ef4d4'
down_revision = '11a174853f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('destination', sa.String(length=15), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['telafric_subscribers.id'], name=op.f('fk_call_logs_subscriber_id_telafric_subscribers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_logs')
    # ### end Alembic commands ###
