"""empty message

Revision ID: 27e95effe070
Revises: ba415bc2dd53
Create Date: 2024-06-11 09:11:10.000953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e95effe070'
down_revision = 'ba415bc2dd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_knowledgebase', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_column('main_knowledgebase')

    # ### end Alembic commands ###
