"""empty message

Revision ID: 379e82c20292
Revises: c42668992c0e
Create Date: 2024-04-27 13:24:25.367335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e82c20292'
down_revision = 'c42668992c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_conversation_history_chatbot_id_chatbots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_history'))
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('conversation_history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_chat_chatbot_id_chatbots')),
    sa.ForeignKeyConstraint(['conversation_history_id'], ['conversation_history.id'], name=op.f('fk_chat_conversation_history_id_conversation_history')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('conversation_history')
    # ### end Alembic commands ###
