"""empty message

Revision ID: 3d8e616e4e4a
Revises: 2707447ef4d4
Create Date: 2024-12-11 09:19:36.975780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8e616e4e4a'
down_revision = '2707447ef4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_prefix', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('rate_per_minute', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rates'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('balance')
        batch_op.drop_column('pin_code')

    op.drop_table('rates')
    # ### end Alembic commands ###
