"""empty message

Revision ID: 4cd6dc9794fd
Revises: 5cde5d06bea1
Create Date: 2024-12-15 12:47:50.159830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd6dc9794fd'
down_revision = '5cde5d06bea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregator', sa.String(length=64), nullable=True))
        batch_op.drop_column('aggrefator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggrefator', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('aggregator')

    # ### end Alembic commands ###
