"""empty message

Revision ID: 5cde5d06bea1
Revises: cfb3e5b95aad
Create Date: 2024-12-15 11:57:11.801860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cde5d06bea1'
down_revision = 'cfb3e5b95aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggrefator', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('aggrefator')

    # ### end Alembic commands ###
