"""empty message

Revision ID: 62ddfbf94014
Revises: 813a99cf3a13
Create Date: 2024-12-12 10:20:03.221705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ddfbf94014'
down_revision = '813a99cf3a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_call_logs_subscriber_id_telafric_subscribers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_call_logs_subscriber_id_users'), 'users', ['subscriber_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_call_logs_subscriber_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_call_logs_subscriber_id_telafric_subscribers', 'telafric_subscribers', ['subscriber_id'], ['id'])

    # ### end Alembic commands ###
