"""empty message

Revision ID: 7056c966c396
Revises: 371f54d485a3
Create Date: 2024-04-28 19:21:09.900409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7056c966c396'
down_revision = '371f54d485a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('foods')
    op.drop_table('restaurants')
    op.drop_table('comments')
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('likeable_id', sa.INTEGER(), nullable=False),
    sa.Column('likeable_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('food_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name='fk_favorites_food_id_foods'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_favorites_restaurant_id_restaurants'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_favorites')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_comments_restaurant_id_restaurants'),
    sa.PrimaryKeyConstraint('id', name='pk_comments')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact3', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image2', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image3', sa.VARCHAR(length=120), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_restaurants')
    )
    op.create_table('foods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_foods_category_id_categories'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_foods_restaurant_id_restaurants'),
    sa.PrimaryKeyConstraint('id', name='pk_foods')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_categories')
    )
    # ### end Alembic commands ###
