"""empty message

Revision ID: 813a99cf3a13
Revises: 3d8e616e4e4a
Create Date: 2024-12-11 09:21:07.343854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813a99cf3a13'
down_revision = '3d8e616e4e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('pin_code')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('number', sa.VARCHAR(length=128), nullable=True),
    sa.Column('location', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('is_organization', sa.BOOLEAN(), nullable=True),
    sa.Column('pin_code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_users_organization_id_organizations'),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    # ### end Alembic commands ###
