"""empty message

Revision ID: ba415bc2dd53
Revises: ba384da30e53
Create Date: 2024-04-29 20:26:24.493615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba415bc2dd53'
down_revision = 'ba384da30e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledgebases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcribed_audio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledgebases', schema=None) as batch_op:
        batch_op.drop_column('transcribed_audio')

    # ### end Alembic commands ###
