"""empty message

Revision ID: c42668992c0e
Revises: 19779b5adbb4
Create Date: 2024-04-26 21:44:18.365688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42668992c0e'
down_revision = '19779b5adbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chatbots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chatbots'))
    )
    op.create_table('knowledgebases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_kb', sa.Text(), nullable=True),
    sa.Column('kb_type', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('image_location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name=op.f('fk_knowledgebases_chatbot_id_chatbots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledgebases'))
    )
    op.drop_table('issues')
    op.drop_table('discussioncomments')
    op.drop_table('polls')
    op.drop_table('upload')
    op.drop_table('discussions')
    op.drop_table('organizations')
    op.drop_table('polloptions')
    op.drop_table('pollvotes')
    op.drop_table('issuecomments')
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('likeable_id', sa.INTEGER(), nullable=False),
    sa.Column('likeable_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=True),
    sa.Column('issue_id', sa.INTEGER(), nullable=True),
    sa.Column('discussion_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name='fk_likes_discussion_id_discussions'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name='fk_likes_issue_id_issues'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_likes_organization_id_organizations'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name='fk_likes_poll_id_polls'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_likes_restaurant_id_restaurants'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_likes_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_likes')
    )
    op.create_table('issuecomments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('issue_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name='fk_issuecomments_issue_id_issues'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['issuecomments.id'], name='fk_issuecomments_parent_comment_id_issuecomments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_issuecomments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_issuecomments')
    )
    op.create_table('pollvotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('option_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['polloptions.id'], name='fk_pollvotes_option_id_polloptions'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name='fk_pollvotes_poll_id_polls'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_pollvotes_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pollvotes')
    )
    op.create_table('polloptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=True),
    sa.Column('option_text', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name='fk_polloptions_poll_id_polls'),
    sa.PrimaryKeyConstraint('id', name='pk_polloptions')
    )
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=64), nullable=False),
    sa.Column('location', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=254), nullable=True),
    sa.Column('workhours', sa.VARCHAR(length=254), nullable=True),
    sa.Column('attachment1', sa.VARCHAR(length=254), nullable=True),
    sa.Column('attachment2', sa.VARCHAR(length=254), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('disklikes', sa.VARCHAR(length=254), nullable=True),
    sa.Column('views', sa.VARCHAR(length=254), nullable=True),
    sa.Column('likes', sa.VARCHAR(length=254), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_organizations_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_organizations')
    )
    op.create_table('discussions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('views', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dislikes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_discussions_organization_id_organizations'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_discussions_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_discussions')
    )
    op.create_table('upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('issue_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name='fk_upload_issue_id_issues'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_upload_organization_id_organizations'),
    sa.PrimaryKeyConstraint('id', name='pk_upload')
    )
    op.create_table('polls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_polls_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_polls')
    )
    op.create_table('discussioncomments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('discussion_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name='fk_discussioncomments_discussion_id_discussions'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['discussioncomments.id'], name='fk_discussioncomments_parent_comment_id_discussioncomments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_discussioncomments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_discussioncomments')
    )
    op.create_table('issues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image2', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image3', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image4', sa.VARCHAR(length=120), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_issues_organization_id_organizations'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_issues_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_issues')
    )
    op.drop_table('knowledgebases')
    op.drop_table('chatbots')
    # ### end Alembic commands ###
