"""empty message

Revision ID: dbdfc866bc1f
Revises: 62ddfbf94014
Create Date: 2024-12-15 10:17:23.221111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdfc866bc1f'
down_revision = '62ddfbf94014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
