"""empty message

Revision ID: dc2017f393ef
Revises: 1f4f86d83ce6
Create Date: 2024-04-28 18:50:32.949859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2017f393ef'
down_revision = '1f4f86d83ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('org_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('org_code', name=op.f('uq_organizations_org_code'))
    )
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chatbots_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chatbots_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_column('organization_id')

    op.drop_table('organizations')
    # ### end Alembic commands ###
