"""empty message

Revision ID: e7c9bc3a551c
Revises: 27e95effe070
Create Date: 2024-10-16 10:27:52.019807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c9bc3a551c'
down_revision = '27e95effe070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tel_afric_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('pin_code', sa.String(length=6), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tel_afric_subscribers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tel_afric_subscribers')
    # ### end Alembic commands ###
