"""empty message

Revision ID: f9eb4a35c1f1
Revises: 7056c966c396
Create Date: 2024-04-28 19:31:48.460651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eb4a35c1f1'
down_revision = '7056c966c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberofusers', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('numberofknowledgebases', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('numberofknowledgebases')
        batch_op.drop_column('numberofusers')

    # ### end Alembic commands ###
